/*
 * Decompiled with CFR 0_132 Helper by Lightcolour E-mail wyy-666@hotmail.com.
 */
package me.slowly.client.util.fontmanager;

import java.awt.Font;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import me.slowly.client.util.fontmanager.UnicodeFontRenderer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.LanguageManager;

public class FontManager {
    private HashMap<String, HashMap<Float, UnicodeFontRenderer>> fonts = new HashMap();
    public UnicodeFontRenderer lemonMilkBold60 = this.getFont("LemonMilkbold", 60.0f, true);
    public UnicodeFontRenderer lemonMilkBold75 = this.getFont("LemonMilkbold", 75.0f, true);
    public UnicodeFontRenderer lemonMilkBold80 = this.getFont("LemonMilkbold", 80.0f, true);
    public UnicodeFontRenderer lemonMilkBold90 = this.getFont("LemonMilkbold", 90.0f, true);
    public UnicodeFontRenderer lemonMilkBold100 = this.getFont("LemonMilkbold", 100.0f, true);
    public UnicodeFontRenderer lemonMilkBold110 = this.getFont("LemonMilkbold", 110.0f, true);
    public UnicodeFontRenderer lemonMilkBold120 = this.getFont("LemonMilkbold", 120.0f, true);
    public UnicodeFontRenderer lemonMilk60 = this.getFont("LemonMilk", 60.0f, true);
    public UnicodeFontRenderer lemonMilk75 = this.getFont("LemonMilk", 75.0f, true);
    public UnicodeFontRenderer lemonMilk80 = this.getFont("LemonMilk", 80.0f, true);
    public UnicodeFontRenderer lemonMilk90 = this.getFont("LemonMilk", 90.0f, true);
    public UnicodeFontRenderer lemonMilk100 = this.getFont("LemonMilk", 100.0f, true);
    public UnicodeFontRenderer lemonMilk110 = this.getFont("LemonMilk", 110.0f, true);
    public UnicodeFontRenderer lemonMilk120 = this.getFont("LemonMilk", 120.0f, true);
    public UnicodeFontRenderer lemonMilklight60 = this.getFont("LemonMilklight", 60.0f, true);
    public UnicodeFontRenderer lemonMilklight75 = this.getFont("LemonMilklight", 75.0f, true);
    public UnicodeFontRenderer lemonMilkLight80 = this.getFont("LemonMilklight", 80.0f, true);
    public UnicodeFontRenderer lemonMilkLight90 = this.getFont("LemonMilklight", 90.0f, true);
    public UnicodeFontRenderer lemonMilkLight100 = this.getFont("LemonMilklight", 100.0f, true);
    public UnicodeFontRenderer lemonMilkLight110 = this.getFont("LemonMilklight", 110.0f, true);
    public UnicodeFontRenderer lemonMilkLight120 = this.getFont("LemonMilklight", 120.0f, true);
    public UnicodeFontRenderer consolasbold10 = this.getFont("consolasbold", 10.0f);
    public UnicodeFontRenderer consolasbold11 = this.getFont("consolasbold", 11.0f);
    public UnicodeFontRenderer consolasbold12 = this.getFont("consolasbold", 12.0f);
    public UnicodeFontRenderer consolasbold13 = this.getFont("consolasbold", 13.0f);
    public UnicodeFontRenderer consolasbold14 = this.getFont("consolasbold", 14.0f);
    public UnicodeFontRenderer consolasbold15 = this.getFont("consolasbold", 15.0f);
    public UnicodeFontRenderer consolasbold16 = this.getFont("consolasbold", 16.0f);
    public UnicodeFontRenderer consolasbold17 = this.getFont("consolasbold", 17.0f);
    public UnicodeFontRenderer consolasbold18 = this.getFont("consolasbold", 18.0f);
    public UnicodeFontRenderer consolasbold20 = this.getFont("consolasbold", 20.0f);
    public UnicodeFontRenderer consolasbold25 = this.getFont("consolasbold", 25.0f);
    public UnicodeFontRenderer consolasbold30 = this.getFont("consolasbold", 30.0f);
    public UnicodeFontRenderer consolasbold35 = this.getFont("consolasbold", 35.0f);
    public UnicodeFontRenderer consolasbold40 = this.getFont("consolasbold", 40.0f);
    public UnicodeFontRenderer consolasbold45 = this.getFont("consolasbold", 45.0f);
    public UnicodeFontRenderer consolasbold50 = this.getFont("consolasbold", 50.0f);
    public UnicodeFontRenderer consolasbold70 = this.getFont("consolasbold", 70.0f);
    public UnicodeFontRenderer logo10 = this.getFont("logo", 10.0f);
    public UnicodeFontRenderer logo11 = this.getFont("logo", 11.0f);
    public UnicodeFontRenderer logo12 = this.getFont("logo", 12.0f);
    public UnicodeFontRenderer logo13 = this.getFont("logo", 13.0f);
    public UnicodeFontRenderer logo14 = this.getFont("logo", 14.0f);
    public UnicodeFontRenderer logo15 = this.getFont("logo", 15.0f);
    public UnicodeFontRenderer logo16 = this.getFont("logo", 16.0f);
    public UnicodeFontRenderer logo17 = this.getFont("logo", 17.0f);
    public UnicodeFontRenderer logo18 = this.getFont("logo", 18.0f);
    public UnicodeFontRenderer logo20 = this.getFont("logo", 20.0f);
    public UnicodeFontRenderer logo25 = this.getFont("logo", 25.0f);
    public UnicodeFontRenderer logo30 = this.getFont("logo", 30.0f);
    public UnicodeFontRenderer logo35 = this.getFont("logo", 35.0f);
    public UnicodeFontRenderer logo40 = this.getFont("logo", 40.0f);
    public UnicodeFontRenderer logo45 = this.getFont("logo", 45.0f);
    public UnicodeFontRenderer logo50 = this.getFont("logo", 50.0f);
    public UnicodeFontRenderer logo70 = this.getFont("logo", 70.0f);
    public UnicodeFontRenderer sant10 = this.getFont("sant", 10.0f);
    public UnicodeFontRenderer sant11 = this.getFont("sant", 11.0f);
    public UnicodeFontRenderer sant12 = this.getFont("sant", 12.0f);
    public UnicodeFontRenderer sant13 = this.getFont("sant", 13.0f);
    public UnicodeFontRenderer sant14 = this.getFont("sant", 14.0f);
    public UnicodeFontRenderer sant15 = this.getFont("sant", 15.0f);
    public UnicodeFontRenderer sant16 = this.getFont("sant", 16.0f);
    public UnicodeFontRenderer sant17 = this.getFont("sant", 17.0f);
    public UnicodeFontRenderer sant18 = this.getFont("sant", 18.0f);
    public UnicodeFontRenderer sant20 = this.getFont("sant", 20.0f);
    public UnicodeFontRenderer sant25 = this.getFont("sant", 25.0f);
    public UnicodeFontRenderer sant30 = this.getFont("sant", 30.0f);
    public UnicodeFontRenderer sant35 = this.getFont("sant", 35.0f);
    public UnicodeFontRenderer sant40 = this.getFont("sant", 40.0f);
    public UnicodeFontRenderer sant45 = this.getFont("sant", 45.0f);
    public UnicodeFontRenderer sant50 = this.getFont("sant", 50.0f);
    public UnicodeFontRenderer sant70 = this.getFont("sant", 70.0f);
    public UnicodeFontRenderer consolas10 = this.getFont("consolas", 10.0f);
    public UnicodeFontRenderer consolas11 = this.getFont("consolas", 11.0f);
    public UnicodeFontRenderer consolas12 = this.getFont("consolas", 12.0f);
    public UnicodeFontRenderer consolas13 = this.getFont("consolas", 13.0f);
    public UnicodeFontRenderer consolas14 = this.getFont("consolas", 14.0f);
    public UnicodeFontRenderer consolas15 = this.getFont("consolas", 15.0f);
    public UnicodeFontRenderer consolas16 = this.getFont("consolas", 16.0f);
    public UnicodeFontRenderer consolas17 = this.getFont("consolas", 17.0f);
    public UnicodeFontRenderer consolas18 = this.getFont("consolas", 18.0f);
    public UnicodeFontRenderer consolas20 = this.getFont("consolas", 20.0f);
    public UnicodeFontRenderer consolas25 = this.getFont("consolas", 25.0f);
    public UnicodeFontRenderer consolas30 = this.getFont("consolas", 30.0f);
    public UnicodeFontRenderer consolas35 = this.getFont("consolas", 35.0f);
    public UnicodeFontRenderer consolas40 = this.getFont("consolas", 40.0f);
    public UnicodeFontRenderer consolas45 = this.getFont("consolas", 45.0f);
    public UnicodeFontRenderer consolas50 = this.getFont("consolas", 50.0f);
    public UnicodeFontRenderer consolas70 = this.getFont("consolas", 70.0f);
    public UnicodeFontRenderer noodle10 = this.getFont("noodle", 10.0f);
    public UnicodeFontRenderer noodle11 = this.getFont("noodle", 11.0f);
    public UnicodeFontRenderer noodle12 = this.getFont("noodle", 12.0f);
    public UnicodeFontRenderer noodle13 = this.getFont("noodle", 13.0f);
    public UnicodeFontRenderer noodle14 = this.getFont("noodle", 14.0f);
    public UnicodeFontRenderer noodle15 = this.getFont("noodle", 15.0f);
    public UnicodeFontRenderer noodle16 = this.getFont("noodle", 16.0f);
    public UnicodeFontRenderer noodle17 = this.getFont("noodle", 17.0f);
    public UnicodeFontRenderer noodle18 = this.getFont("noodle", 18.0f);
    public UnicodeFontRenderer noodle20 = this.getFont("noodle", 20.0f);
    public UnicodeFontRenderer noodle21 = this.getFont("noodle", 21.0f);
    public UnicodeFontRenderer noodle22 = this.getFont("noodle", 22.0f);
    public UnicodeFontRenderer noodle23 = this.getFont("noodle", 23.0f);
    public UnicodeFontRenderer noodle24 = this.getFont("noodle", 24.0f);
    public UnicodeFontRenderer noodle25 = this.getFont("noodle", 25.0f);
    public UnicodeFontRenderer noodle30 = this.getFont("noodle", 30.0f);
    public UnicodeFontRenderer noodle35 = this.getFont("noodle", 35.0f);
    public UnicodeFontRenderer noodle40 = this.getFont("noodle", 40.0f);
    public UnicodeFontRenderer noodle45 = this.getFont("noodle", 45.0f);
    public UnicodeFontRenderer noodle50 = this.getFont("noodle", 50.0f);
    public UnicodeFontRenderer noodle70 = this.getFont("noodle", 70.0f);
    public UnicodeFontRenderer comfortaa10 = this.getFont("comfortaa", 10.0f);
    public UnicodeFontRenderer comfortaa11 = this.getFont("comfortaa", 11.0f);
    public UnicodeFontRenderer comfortaa12 = this.getFont("comfortaa", 12.0f);
    public UnicodeFontRenderer comfortaa13 = this.getFont("comfortaa", 13.0f);
    public UnicodeFontRenderer comfortaa15 = this.getFont("comfortaa", 15.0f);
    public UnicodeFontRenderer comfortaa16 = this.getFont("comfortaa", 16.0f);
    public UnicodeFontRenderer comfortaa17 = this.getFont("comfortaa", 17.0f);
    public UnicodeFontRenderer comfortaa18 = this.getFont("comfortaa", 18.0f);
    public UnicodeFontRenderer comfortaa20 = this.getFont("comfortaa", 20.0f);
    public UnicodeFontRenderer comfortaa25 = this.getFont("comfortaa", 25.0f);
    public UnicodeFontRenderer comfortaa30 = this.getFont("comfortaa", 30.0f);
    public UnicodeFontRenderer comfortaa35 = this.getFont("comfortaa", 35.0f);
    public UnicodeFontRenderer comfortaa40 = this.getFont("comfortaa", 40.0f);
    public UnicodeFontRenderer comfortaa45 = this.getFont("comfortaa", 45.0f);
    public UnicodeFontRenderer comfortaa50 = this.getFont("comfortaa", 50.0f);
    public UnicodeFontRenderer comfortaa70 = this.getFont("comfortaa", 70.0f);
    public UnicodeFontRenderer verdanalight10 = this.getFont("verdanalight", 10.0f);
    public UnicodeFontRenderer verdanalight11 = this.getFont("verdanalight", 11.0f);
    public UnicodeFontRenderer verdanalight12 = this.getFont("verdanalight", 12.0f);
    public UnicodeFontRenderer verdanalight13 = this.getFont("verdanalight", 13.0f);
    public UnicodeFontRenderer verdanalight15 = this.getFont("verdanalight", 15.0f);
    public UnicodeFontRenderer verdanalight16 = this.getFont("verdanalight", 16.0f);
    public UnicodeFontRenderer verdanalight17 = this.getFont("verdanalight", 17.0f);
    public UnicodeFontRenderer verdanalight18 = this.getFont("verdanalight", 18.0f);
    public UnicodeFontRenderer verdanalight20 = this.getFont("verdanalight", 20.0f);
    public UnicodeFontRenderer verdanalight25 = this.getFont("verdanalight", 25.0f);
    public UnicodeFontRenderer verdanalight30 = this.getFont("verdanalight", 30.0f);
    public UnicodeFontRenderer verdanalight35 = this.getFont("verdanalight", 35.0f);
    public UnicodeFontRenderer verdanalight40 = this.getFont("verdanalight", 40.0f);
    public UnicodeFontRenderer verdanalight45 = this.getFont("verdanalight", 45.0f);
    public UnicodeFontRenderer verdanalight50 = this.getFont("verdanalight", 50.0f);
    public UnicodeFontRenderer verdanalight70 = this.getFont("verdanalight", 70.0f);
    public UnicodeFontRenderer lane10 = this.getFont("lane", 10.0f);
    public UnicodeFontRenderer lane11 = this.getFont("lane", 11.0f);
    public UnicodeFontRenderer lane12 = this.getFont("lane", 12.0f);
    public UnicodeFontRenderer lane13 = this.getFont("lane", 13.0f);
    public UnicodeFontRenderer lane15 = this.getFont("lane", 15.0f);
    public UnicodeFontRenderer lane16 = this.getFont("lane", 16.0f);
    public UnicodeFontRenderer lane17 = this.getFont("lane", 17.0f);
    public UnicodeFontRenderer lane18 = this.getFont("lane", 18.0f);
    public UnicodeFontRenderer lane20 = this.getFont("lane", 20.0f);
    public UnicodeFontRenderer lane25 = this.getFont("lane", 25.0f);
    public UnicodeFontRenderer lane30 = this.getFont("lane", 30.0f);
    public UnicodeFontRenderer lane35 = this.getFont("lane", 35.0f);
    public UnicodeFontRenderer lane40 = this.getFont("lane", 40.0f);
    public UnicodeFontRenderer lane45 = this.getFont("lane", 45.0f);
    public UnicodeFontRenderer lane50 = this.getFont("lane", 50.0f);
    public UnicodeFontRenderer lane70 = this.getFont("lane", 70.0f);
    public UnicodeFontRenderer simpleton10 = this.getFont("simpleton", 10.0f, true);
    public UnicodeFontRenderer simpleton11 = this.getFont("simpleton", 11.0f, true);
    public UnicodeFontRenderer simpleton12 = this.getFont("simpleton", 12.0f, true);
    public UnicodeFontRenderer simpleton13 = this.getFont("simpleton", 13.0f, true);
    public UnicodeFontRenderer simpleton15 = this.getFont("simpleton", 15.0f, true);
    public UnicodeFontRenderer simpleton16 = this.getFont("simpleton", 16.0f, true);
    public UnicodeFontRenderer simpleton17 = this.getFont("simpleton", 17.0f, true);
    public UnicodeFontRenderer simpleton18 = this.getFont("simpleton", 18.0f, true);
    public UnicodeFontRenderer simpleton20 = this.getFont("simpleton", 20.0f, true);
    public UnicodeFontRenderer simpleton25 = this.getFont("simpleton", 25.0f, true);
    public UnicodeFontRenderer simpleton30 = this.getFont("simpleton", 30.0f, true);
    public UnicodeFontRenderer simpleton35 = this.getFont("simpleton", 35.0f, true);
    public UnicodeFontRenderer simpleton40 = this.getFont("simpleton", 40.0f, true);
    public UnicodeFontRenderer simpleton45 = this.getFont("simpleton", 45.0f, true);
    public UnicodeFontRenderer simpleton50 = this.getFont("simpleton", 50.0f, true);
    public UnicodeFontRenderer simpleton70 = this.getFont("simpleton", 70.0f, true);
    public UnicodeFontRenderer gravity10 = this.getFont("gravity", 10.0f, true);
    public UnicodeFontRenderer gravity11 = this.getFont("gravity", 11.0f, true);
    public UnicodeFontRenderer gravity12 = this.getFont("gravity", 12.0f, true);
    public UnicodeFontRenderer gravity13 = this.getFont("gravity", 13.0f, true);
    public UnicodeFontRenderer gravity15 = this.getFont("gravity", 15.0f, true);
    public UnicodeFontRenderer gravity16 = this.getFont("gravity", 16.0f, true);
    public UnicodeFontRenderer gravity17 = this.getFont("gravity", 17.0f, true);
    public UnicodeFontRenderer gravity18 = this.getFont("gravity", 18.0f, true);
    public UnicodeFontRenderer gravity20 = this.getFont("gravity", 20.0f, true);
    public UnicodeFontRenderer gravity25 = this.getFont("gravity", 25.0f, true);
    public UnicodeFontRenderer gravity30 = this.getFont("gravity", 30.0f, true);
    public UnicodeFontRenderer gravity35 = this.getFont("gravity", 35.0f, true);
    public UnicodeFontRenderer gravity40 = this.getFont("gravity", 40.0f, true);
    public UnicodeFontRenderer gravity45 = this.getFont("gravity", 45.0f, true);
    public UnicodeFontRenderer gravity50 = this.getFont("gravity", 50.0f, true);
    public UnicodeFontRenderer gravity70 = this.getFont("gravity", 70.0f, true);
    public UnicodeFontRenderer Bebas10 = this.getFont("Bebas", 10.0f, true);
    public UnicodeFontRenderer Bebas11 = this.getFont("Bebas", 11.0f, true);
    public UnicodeFontRenderer Bebas12 = this.getFont("Bebas", 12.0f, true);
    public UnicodeFontRenderer Bebas13 = this.getFont("Bebas", 13.0f, true);
    public UnicodeFontRenderer Bebas15 = this.getFont("Bebas", 15.0f, true);
    public UnicodeFontRenderer Bebas16 = this.getFont("Bebas", 16.0f, true);
    public UnicodeFontRenderer Bebas17 = this.getFont("Bebas", 17.0f, true);
    public UnicodeFontRenderer Bebas18 = this.getFont("Bebas", 18.0f, true);
    public UnicodeFontRenderer Bebas20 = this.getFont("Bebas", 20.0f, true);
    public UnicodeFontRenderer Bebas21 = this.getFont("Bebas", 21.0f, true);
    public UnicodeFontRenderer Bebas25 = this.getFont("Bebas", 25.0f, true);
    public UnicodeFontRenderer Bebas30 = this.getFont("Bebas", 30.0f, true);
    public UnicodeFontRenderer Bebas35 = this.getFont("Bebas", 35.0f, true);
    public UnicodeFontRenderer Bebas40 = this.getFont("Bebas", 40.0f, true);
    public UnicodeFontRenderer Bebas45 = this.getFont("Bebas", 45.0f, true);
    public UnicodeFontRenderer Bebas50 = this.getFont("Bebas", 50.0f, true);
    public UnicodeFontRenderer Bebas70 = this.getFont("Bebas", 70.0f, true);
    public UnicodeFontRenderer payback10 = this.getFont("payback", 10.0f);
    public UnicodeFontRenderer payback11 = this.getFont("payback", 11.0f);
    public UnicodeFontRenderer payback12 = this.getFont("payback", 12.0f);
    public UnicodeFontRenderer payback13 = this.getFont("payback", 13.0f);
    public UnicodeFontRenderer payback15 = this.getFont("payback", 15.0f);
    public UnicodeFontRenderer payback16 = this.getFont("payback", 16.0f);
    public UnicodeFontRenderer payback17 = this.getFont("payback", 17.0f);
    public UnicodeFontRenderer payback18 = this.getFont("payback", 18.0f);
    public UnicodeFontRenderer payback20 = this.getFont("payback", 20.0f);
    public UnicodeFontRenderer payback25 = this.getFont("payback", 25.0f);
    public UnicodeFontRenderer payback30 = this.getFont("payback", 30.0f);
    public UnicodeFontRenderer payback35 = this.getFont("payback", 35.0f);
    public UnicodeFontRenderer payback40 = this.getFont("payback", 40.0f);
    public UnicodeFontRenderer payback45 = this.getFont("payback", 45.0f);
    public UnicodeFontRenderer payback50 = this.getFont("payback", 50.0f);
    public UnicodeFontRenderer payback70 = this.getFont("payback", 70.0f);
    public UnicodeFontRenderer cabin10 = this.getFont("cabin", 10.0f);
    public UnicodeFontRenderer cabin11 = this.getFont("cabin", 11.0f);
    public UnicodeFontRenderer cabin12 = this.getFont("cabin", 12.0f);
    public UnicodeFontRenderer cabin13 = this.getFont("cabin", 13.0f);
    public UnicodeFontRenderer cabin15 = this.getFont("cabin", 15.0f);
    public UnicodeFontRenderer cabin16 = this.getFont("cabin", 16.0f);
    public UnicodeFontRenderer cabin17 = this.getFont("cabin", 17.0f);
    public UnicodeFontRenderer cabin18 = this.getFont("cabin", 18.0f);
    public UnicodeFontRenderer cabin20 = this.getFont("cabin", 20.0f);
    public UnicodeFontRenderer cabin25 = this.getFont("cabin", 25.0f);
    public UnicodeFontRenderer cabin30 = this.getFont("cabin", 30.0f);
    public UnicodeFontRenderer cabin35 = this.getFont("cabin", 35.0f);
    public UnicodeFontRenderer cabin40 = this.getFont("cabin", 40.0f);
    public UnicodeFontRenderer cabin45 = this.getFont("cabin", 45.0f);
    public UnicodeFontRenderer cabin50 = this.getFont("cabin", 50.0f);
    public UnicodeFontRenderer cabin70 = this.getFont("cabin", 70.0f);
    public UnicodeFontRenderer VERDANA10 = this.getFont("VERDANA", 10.0f);
    public UnicodeFontRenderer VERDANA11 = this.getFont("VERDANA", 11.0f);
    public UnicodeFontRenderer VERDANA12 = this.getFont("VERDANA", 12.0f);
    public UnicodeFontRenderer VERDANA13 = this.getFont("VERDANA", 13.0f);
    public UnicodeFontRenderer VERDANA15 = this.getFont("VERDANA", 15.0f);
    public UnicodeFontRenderer VERDANA16 = this.getFont("VERDANA", 16.0f);
    public UnicodeFontRenderer VERDANA17 = this.getFont("VERDANA", 17.0f);
    public UnicodeFontRenderer VERDANA18 = this.getFont("VERDANA", 18.0f);
    public UnicodeFontRenderer VERDANA20 = this.getFont("VERDANA", 20.0f);
    public UnicodeFontRenderer VERDANA25 = this.getFont("VERDANA", 25.0f);
    public UnicodeFontRenderer VERDANA30 = this.getFont("VERDANA", 30.0f);
    public UnicodeFontRenderer VERDANA35 = this.getFont("VERDANA", 35.0f);
    public UnicodeFontRenderer VERDANA40 = this.getFont("VERDANA", 40.0f);
    public UnicodeFontRenderer VERDANA45 = this.getFont("VERDANA", 45.0f);
    public UnicodeFontRenderer VERDANA50 = this.getFont("VERDANA", 50.0f);
    public UnicodeFontRenderer arialBold10 = this.getFont("arialBold", 10.0f);
    public UnicodeFontRenderer arialBold11 = this.getFont("arialBold", 11.0f);
    public UnicodeFontRenderer arialBold12 = this.getFont("arialBold", 12.0f);
    public UnicodeFontRenderer arialBold13 = this.getFont("arialBold", 13.0f);
    public UnicodeFontRenderer arialBold15 = this.getFont("arialBold", 15.0f);
    public UnicodeFontRenderer arialBold16 = this.getFont("arialBold", 16.0f);
    public UnicodeFontRenderer arialBold17 = this.getFont("arialBold", 17.0f);
    public UnicodeFontRenderer arialBold18 = this.getFont("arialBold", 18.0f);
    public UnicodeFontRenderer arialBold20 = this.getFont("arialBold", 20.0f);
    public UnicodeFontRenderer arialBold25 = this.getFont("arialBold", 25.0f);
    public UnicodeFontRenderer arialBold30 = this.getFont("arialBold", 30.0f);
    public UnicodeFontRenderer arialBold35 = this.getFont("arialBold", 35.0f);
    public UnicodeFontRenderer arialBold40 = this.getFont("arialBold", 40.0f);
    public UnicodeFontRenderer arialBold45 = this.getFont("arialBold", 45.0f);
    public UnicodeFontRenderer arialBold50 = this.getFont("arialBold", 50.0f);
    public UnicodeFontRenderer robotobold10 = this.getFont("robotobold", 10.0f);
    public UnicodeFontRenderer robotobold11 = this.getFont("robotobold", 11.0f);
    public UnicodeFontRenderer robotobold12 = this.getFont("robotobold", 12.0f);
    public UnicodeFontRenderer robotobold13 = this.getFont("robotobold", 13.0f);
    public UnicodeFontRenderer robotobold15 = this.getFont("robotobold", 15.0f);
    public UnicodeFontRenderer robotobold16 = this.getFont("robotobold", 16.0f);
    public UnicodeFontRenderer robotobold17 = this.getFont("robotobold", 17.0f);
    public UnicodeFontRenderer robotobold18 = this.getFont("robotobold", 18.0f);
    public UnicodeFontRenderer robotobold20 = this.getFont("robotobold", 20.0f);
    public UnicodeFontRenderer robotobold25 = this.getFont("robotobold", 25.0f);
    public UnicodeFontRenderer robotobold30 = this.getFont("robotobold", 30.0f);
    public UnicodeFontRenderer robotobold35 = this.getFont("robotobold", 35.0f);
    public UnicodeFontRenderer robotobold40 = this.getFont("robotobold", 40.0f);
    public UnicodeFontRenderer robotobold45 = this.getFont("robotobold", 45.0f);
    public UnicodeFontRenderer robotobold50 = this.getFont("robotobold", 50.0f);
    public UnicodeFontRenderer motorblock10 = this.getFont("motorblock", 10.0f);
    public UnicodeFontRenderer motorblock11 = this.getFont("motorblock", 11.0f);
    public UnicodeFontRenderer motorblock12 = this.getFont("motorblock", 12.0f);
    public UnicodeFontRenderer motorblock13 = this.getFont("motorblock", 13.0f);
    public UnicodeFontRenderer motorblock15 = this.getFont("motorblock", 15.0f);
    public UnicodeFontRenderer motorblock16 = this.getFont("motorblock", 16.0f);
    public UnicodeFontRenderer motorblock17 = this.getFont("motorblock", 17.0f);
    public UnicodeFontRenderer motorblock18 = this.getFont("motorblock", 18.0f);
    public UnicodeFontRenderer motorblock20 = this.getFont("motorblock", 20.0f);
    public UnicodeFontRenderer motorblock25 = this.getFont("motorblock", 25.0f);
    public UnicodeFontRenderer motorblock30 = this.getFont("motorblock", 30.0f);
    public UnicodeFontRenderer motorblock35 = this.getFont("motorblock", 35.0f);
    public UnicodeFontRenderer motorblock40 = this.getFont("motorblock", 40.0f);
    public UnicodeFontRenderer motorblock45 = this.getFont("motorblock", 45.0f);
    public UnicodeFontRenderer motorblock50 = this.getFont("motorblock", 50.0f);
    public UnicodeFontRenderer Gotham10 = this.getFont("Gotham", 10.0f);
    public UnicodeFontRenderer Gotham11 = this.getFont("Gotham", 11.0f);
    public UnicodeFontRenderer Gotham12 = this.getFont("Gotham", 12.0f);
    public UnicodeFontRenderer Gotham13 = this.getFont("Gotham", 13.0f);
    public UnicodeFontRenderer Gotham15 = this.getFont("Gotham", 15.0f);
    public UnicodeFontRenderer Gotham16 = this.getFont("Gotham", 16.0f);
    public UnicodeFontRenderer Gotham17 = this.getFont("Gotham", 17.0f);
    public UnicodeFontRenderer Gotham18 = this.getFont("Gotham", 18.0f);
    public UnicodeFontRenderer Gotham20 = this.getFont("Gotham", 20.0f);
    public UnicodeFontRenderer Gotham25 = this.getFont("Gotham", 25.0f);
    public UnicodeFontRenderer Gotham30 = this.getFont("Gotham", 30.0f);
    public UnicodeFontRenderer Gotham35 = this.getFont("Gotham", 35.0f);
    public UnicodeFontRenderer Gotham40 = this.getFont("Gotham", 40.0f);
    public UnicodeFontRenderer Gotham45 = this.getFont("Gotham", 45.0f);
    public UnicodeFontRenderer Gotham50 = this.getFont("Gotham", 50.0f);
    public UnicodeFontRenderer Gotham60 = this.getFont("Gotham", 60.0f);

    public UnicodeFontRenderer getFont(String name, float size) {
        UnicodeFontRenderer unicodeFont = null;
        try {
            if (this.fonts.containsKey(name) && this.fonts.get(name).containsKey(Float.valueOf(size))) {
                return this.fonts.get(name).get(Float.valueOf(size));
            }
            InputStream inputStream = this.getClass().getResourceAsStream("fonts/" + name + ".ttf");
            Font font = null;
            font = Font.createFont(0, inputStream);
            unicodeFont = new UnicodeFontRenderer(font.deriveFont(size));
            unicodeFont.setUnicodeFlag(true);
            unicodeFont.setBidiFlag(Minecraft.getMinecraft().mcLanguageManager.isCurrentLanguageBidirectional());
            HashMap<Float, UnicodeFontRenderer> map = new HashMap<Float, UnicodeFontRenderer>();
            if (this.fonts.containsKey(name)) {
                map.putAll((Map)this.fonts.get(name));
            }
            map.put(Float.valueOf(size), unicodeFont);
            this.fonts.put(name, map);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return unicodeFont;
    }

    public UnicodeFontRenderer getFont(String name, float size, boolean b) {
        UnicodeFontRenderer unicodeFont = null;
        try {
            if (this.fonts.containsKey(name) && this.fonts.get(name).containsKey(Float.valueOf(size))) {
                return this.fonts.get(name).get(Float.valueOf(size));
            }
            InputStream inputStream = this.getClass().getResourceAsStream("fonts/" + name + ".otf");
            Font font = null;
            font = Font.createFont(0, inputStream);
            unicodeFont = new UnicodeFontRenderer(font.deriveFont(size));
            unicodeFont.setUnicodeFlag(true);
            unicodeFont.setBidiFlag(Minecraft.getMinecraft().mcLanguageManager.isCurrentLanguageBidirectional());
            HashMap<Float, UnicodeFontRenderer> map = new HashMap<Float, UnicodeFontRenderer>();
            if (this.fonts.containsKey(name)) {
                map.putAll((Map)this.fonts.get(name));
            }
            map.put(Float.valueOf(size), unicodeFont);
            this.fonts.put(name, map);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return unicodeFont;
    }
}

