// 
// Decompiled by Procyon v0.5.36
// 

package net.java.games.input;

final class KeyboardUsage implements Usage
{
    private static final KeyboardUsage[] map;
    public static final KeyboardUsage ERRORROLLOVER;
    public static final KeyboardUsage POSTFAIL;
    public static final KeyboardUsage ERRORUNDEFINED;
    public static final KeyboardUsage A;
    public static final KeyboardUsage B;
    public static final KeyboardUsage C;
    public static final KeyboardUsage D;
    public static final KeyboardUsage E;
    public static final KeyboardUsage F;
    public static final KeyboardUsage G;
    public static final KeyboardUsage H;
    public static final KeyboardUsage I;
    public static final KeyboardUsage J;
    public static final KeyboardUsage K;
    public static final KeyboardUsage L;
    public static final KeyboardUsage M;
    public static final KeyboardUsage N;
    public static final KeyboardUsage O;
    public static final KeyboardUsage P;
    public static final KeyboardUsage Q;
    public static final KeyboardUsage R;
    public static final KeyboardUsage S;
    public static final KeyboardUsage T;
    public static final KeyboardUsage U;
    public static final KeyboardUsage V;
    public static final KeyboardUsage W;
    public static final KeyboardUsage X;
    public static final KeyboardUsage Y;
    public static final KeyboardUsage Z;
    public static final KeyboardUsage _1;
    public static final KeyboardUsage _2;
    public static final KeyboardUsage _3;
    public static final KeyboardUsage _4;
    public static final KeyboardUsage _5;
    public static final KeyboardUsage _6;
    public static final KeyboardUsage _7;
    public static final KeyboardUsage _8;
    public static final KeyboardUsage _9;
    public static final KeyboardUsage _0;
    public static final KeyboardUsage ENTER;
    public static final KeyboardUsage ESCAPE;
    public static final KeyboardUsage BACKSPACE;
    public static final KeyboardUsage TAB;
    public static final KeyboardUsage SPACEBAR;
    public static final KeyboardUsage HYPHEN;
    public static final KeyboardUsage EQUALSIGN;
    public static final KeyboardUsage OPENBRACKET;
    public static final KeyboardUsage CLOSEBRACKET;
    public static final KeyboardUsage BACKSLASH;
    public static final KeyboardUsage NONUSPOUNT;
    public static final KeyboardUsage SEMICOLON;
    public static final KeyboardUsage QUOTE;
    public static final KeyboardUsage TILDE;
    public static final KeyboardUsage COMMA;
    public static final KeyboardUsage PERIOD;
    public static final KeyboardUsage SLASH;
    public static final KeyboardUsage CAPSLOCK;
    public static final KeyboardUsage F1;
    public static final KeyboardUsage F2;
    public static final KeyboardUsage F3;
    public static final KeyboardUsage F4;
    public static final KeyboardUsage F5;
    public static final KeyboardUsage F6;
    public static final KeyboardUsage F7;
    public static final KeyboardUsage F8;
    public static final KeyboardUsage F9;
    public static final KeyboardUsage F10;
    public static final KeyboardUsage F11;
    public static final KeyboardUsage F12;
    public static final KeyboardUsage PRINTSCREEN;
    public static final KeyboardUsage SCROLLLOCK;
    public static final KeyboardUsage PAUSE;
    public static final KeyboardUsage INSERT;
    public static final KeyboardUsage HOME;
    public static final KeyboardUsage PAGEUP;
    public static final KeyboardUsage DELETE;
    public static final KeyboardUsage END;
    public static final KeyboardUsage PAGEDOWN;
    public static final KeyboardUsage RIGHTARROW;
    public static final KeyboardUsage LEFTARROW;
    public static final KeyboardUsage DOWNARROW;
    public static final KeyboardUsage UPARROW;
    public static final KeyboardUsage KEYPAD_NUMLOCK;
    public static final KeyboardUsage KEYPAD_SLASH;
    public static final KeyboardUsage KEYPAD_ASTERICK;
    public static final KeyboardUsage KEYPAD_HYPHEN;
    public static final KeyboardUsage KEYPAD_PLUS;
    public static final KeyboardUsage KEYPAD_ENTER;
    public static final KeyboardUsage KEYPAD_1;
    public static final KeyboardUsage KEYPAD_2;
    public static final KeyboardUsage KEYPAD_3;
    public static final KeyboardUsage KEYPAD_4;
    public static final KeyboardUsage KEYPAD_5;
    public static final KeyboardUsage KEYPAD_6;
    public static final KeyboardUsage KEYPAD_7;
    public static final KeyboardUsage KEYPAD_8;
    public static final KeyboardUsage KEYPAD_9;
    public static final KeyboardUsage KEYPAD_0;
    public static final KeyboardUsage KEYPAD_PERIOD;
    public static final KeyboardUsage NONUSBACKSLASH;
    public static final KeyboardUsage APPLICATION;
    public static final KeyboardUsage POWER;
    public static final KeyboardUsage KEYPAD_EQUALSIGN;
    public static final KeyboardUsage F13;
    public static final KeyboardUsage F14;
    public static final KeyboardUsage F15;
    public static final KeyboardUsage F16;
    public static final KeyboardUsage F17;
    public static final KeyboardUsage F18;
    public static final KeyboardUsage F19;
    public static final KeyboardUsage F20;
    public static final KeyboardUsage F21;
    public static final KeyboardUsage F22;
    public static final KeyboardUsage F23;
    public static final KeyboardUsage F24;
    public static final KeyboardUsage EXECUTE;
    public static final KeyboardUsage HELP;
    public static final KeyboardUsage MENU;
    public static final KeyboardUsage SELECT;
    public static final KeyboardUsage STOP;
    public static final KeyboardUsage AGAIN;
    public static final KeyboardUsage UNDO;
    public static final KeyboardUsage CUT;
    public static final KeyboardUsage COPY;
    public static final KeyboardUsage PASTE;
    public static final KeyboardUsage FIND;
    public static final KeyboardUsage MUTE;
    public static final KeyboardUsage VOLUMEUP;
    public static final KeyboardUsage VOLUMEDOWN;
    public static final KeyboardUsage LOCKINGCAPSLOCK;
    public static final KeyboardUsage LOCKINGNUMLOCK;
    public static final KeyboardUsage LOCKINGSCROLLLOCK;
    public static final KeyboardUsage KEYPAD_COMMA;
    public static final KeyboardUsage KEYPAD_EQUALSSIGNAS400;
    public static final KeyboardUsage INTERNATIONAL1;
    public static final KeyboardUsage INTERNATIONAL2;
    public static final KeyboardUsage INTERNATIONAL3;
    public static final KeyboardUsage INTERNATIONAL4;
    public static final KeyboardUsage INTERNATIONAL5;
    public static final KeyboardUsage INTERNATIONAL6;
    public static final KeyboardUsage INTERNATIONAL7;
    public static final KeyboardUsage INTERNATIONAL8;
    public static final KeyboardUsage INTERNATIONAL9;
    public static final KeyboardUsage LANG1;
    public static final KeyboardUsage LANG2;
    public static final KeyboardUsage LANG3;
    public static final KeyboardUsage LANG4;
    public static final KeyboardUsage LANG5;
    public static final KeyboardUsage LANG6;
    public static final KeyboardUsage LANG7;
    public static final KeyboardUsage LANG8;
    public static final KeyboardUsage LANG9;
    public static final KeyboardUsage ALTERNATEERASE;
    public static final KeyboardUsage SYSREQORATTENTION;
    public static final KeyboardUsage CANCEL;
    public static final KeyboardUsage CLEAR;
    public static final KeyboardUsage PRIOR;
    public static final KeyboardUsage RETURN;
    public static final KeyboardUsage SEPARATOR;
    public static final KeyboardUsage OUT;
    public static final KeyboardUsage OPER;
    public static final KeyboardUsage CLEARORAGAIN;
    public static final KeyboardUsage CRSELORPROPS;
    public static final KeyboardUsage EXSEL;
    public static final KeyboardUsage LEFTCONTROL;
    public static final KeyboardUsage LEFTSHIFT;
    public static final KeyboardUsage LEFTALT;
    public static final KeyboardUsage LEFTGUI;
    public static final KeyboardUsage RIGHTCONTROL;
    public static final KeyboardUsage RIGHTSHIFT;
    public static final KeyboardUsage RIGHTALT;
    public static final KeyboardUsage RIGHTGUI;
    private final int usage;
    private final Component.Identifier.Key identifier;
    
    public final Component.Identifier.Key getIdentifier() {
        return this.identifier;
    }
    
    public static final KeyboardUsage map(final int usage) {
        if (usage < 0 || usage >= KeyboardUsage.map.length) {
            return null;
        }
        return KeyboardUsage.map[usage];
    }
    
    private KeyboardUsage(final int usage) {
        this(Component.Identifier.Key.UNKNOWN, usage);
    }
    
    private KeyboardUsage(final Component.Identifier.Key id, final int usage) {
        this.identifier = id;
        this.usage = usage;
        KeyboardUsage.map[usage] = this;
    }
    
    public final String toString() {
        return "KeyboardUsage (0x" + Integer.toHexString(this.usage) + ")";
    }
    
    static {
        map = new KeyboardUsage[255];
        ERRORROLLOVER = new KeyboardUsage(1);
        POSTFAIL = new KeyboardUsage(2);
        ERRORUNDEFINED = new KeyboardUsage(3);
        A = new KeyboardUsage(Component.Identifier.Key.A, 4);
        B = new KeyboardUsage(Component.Identifier.Key.B, 5);
        C = new KeyboardUsage(Component.Identifier.Key.C, 6);
        D = new KeyboardUsage(Component.Identifier.Key.D, 7);
        E = new KeyboardUsage(Component.Identifier.Key.E, 8);
        F = new KeyboardUsage(Component.Identifier.Key.F, 9);
        G = new KeyboardUsage(Component.Identifier.Key.G, 10);
        H = new KeyboardUsage(Component.Identifier.Key.H, 11);
        I = new KeyboardUsage(Component.Identifier.Key.I, 12);
        J = new KeyboardUsage(Component.Identifier.Key.J, 13);
        K = new KeyboardUsage(Component.Identifier.Key.K, 14);
        L = new KeyboardUsage(Component.Identifier.Key.L, 15);
        M = new KeyboardUsage(Component.Identifier.Key.M, 16);
        N = new KeyboardUsage(Component.Identifier.Key.N, 17);
        O = new KeyboardUsage(Component.Identifier.Key.O, 18);
        P = new KeyboardUsage(Component.Identifier.Key.P, 19);
        Q = new KeyboardUsage(Component.Identifier.Key.Q, 20);
        R = new KeyboardUsage(Component.Identifier.Key.R, 21);
        S = new KeyboardUsage(Component.Identifier.Key.S, 22);
        T = new KeyboardUsage(Component.Identifier.Key.T, 23);
        U = new KeyboardUsage(Component.Identifier.Key.U, 24);
        V = new KeyboardUsage(Component.Identifier.Key.V, 25);
        W = new KeyboardUsage(Component.Identifier.Key.W, 26);
        X = new KeyboardUsage(Component.Identifier.Key.X, 27);
        Y = new KeyboardUsage(Component.Identifier.Key.Y, 28);
        Z = new KeyboardUsage(Component.Identifier.Key.Z, 29);
        _1 = new KeyboardUsage(Component.Identifier.Key._1, 30);
        _2 = new KeyboardUsage(Component.Identifier.Key._2, 31);
        _3 = new KeyboardUsage(Component.Identifier.Key._3, 32);
        _4 = new KeyboardUsage(Component.Identifier.Key._4, 33);
        _5 = new KeyboardUsage(Component.Identifier.Key._5, 34);
        _6 = new KeyboardUsage(Component.Identifier.Key._6, 35);
        _7 = new KeyboardUsage(Component.Identifier.Key._7, 36);
        _8 = new KeyboardUsage(Component.Identifier.Key._8, 37);
        _9 = new KeyboardUsage(Component.Identifier.Key._9, 38);
        _0 = new KeyboardUsage(Component.Identifier.Key._0, 39);
        ENTER = new KeyboardUsage(Component.Identifier.Key.RETURN, 40);
        ESCAPE = new KeyboardUsage(Component.Identifier.Key.ESCAPE, 41);
        BACKSPACE = new KeyboardUsage(Component.Identifier.Key.BACK, 42);
        TAB = new KeyboardUsage(Component.Identifier.Key.TAB, 43);
        SPACEBAR = new KeyboardUsage(Component.Identifier.Key.SPACE, 44);
        HYPHEN = new KeyboardUsage(Component.Identifier.Key.MINUS, 45);
        EQUALSIGN = new KeyboardUsage(Component.Identifier.Key.EQUALS, 46);
        OPENBRACKET = new KeyboardUsage(Component.Identifier.Key.LBRACKET, 47);
        CLOSEBRACKET = new KeyboardUsage(Component.Identifier.Key.RBRACKET, 48);
        BACKSLASH = new KeyboardUsage(Component.Identifier.Key.BACKSLASH, 49);
        NONUSPOUNT = new KeyboardUsage(Component.Identifier.Key.PERIOD, 50);
        SEMICOLON = new KeyboardUsage(Component.Identifier.Key.SEMICOLON, 51);
        QUOTE = new KeyboardUsage(Component.Identifier.Key.APOSTROPHE, 52);
        TILDE = new KeyboardUsage(Component.Identifier.Key.GRAVE, 53);
        COMMA = new KeyboardUsage(Component.Identifier.Key.COMMA, 54);
        PERIOD = new KeyboardUsage(Component.Identifier.Key.PERIOD, 55);
        SLASH = new KeyboardUsage(Component.Identifier.Key.SLASH, 56);
        CAPSLOCK = new KeyboardUsage(Component.Identifier.Key.CAPITAL, 57);
        F1 = new KeyboardUsage(Component.Identifier.Key.F1, 58);
        F2 = new KeyboardUsage(Component.Identifier.Key.F2, 59);
        F3 = new KeyboardUsage(Component.Identifier.Key.F3, 60);
        F4 = new KeyboardUsage(Component.Identifier.Key.F4, 61);
        F5 = new KeyboardUsage(Component.Identifier.Key.F5, 62);
        F6 = new KeyboardUsage(Component.Identifier.Key.F6, 63);
        F7 = new KeyboardUsage(Component.Identifier.Key.F7, 64);
        F8 = new KeyboardUsage(Component.Identifier.Key.F8, 65);
        F9 = new KeyboardUsage(Component.Identifier.Key.F9, 66);
        F10 = new KeyboardUsage(Component.Identifier.Key.F10, 67);
        F11 = new KeyboardUsage(Component.Identifier.Key.F11, 68);
        F12 = new KeyboardUsage(Component.Identifier.Key.F12, 69);
        PRINTSCREEN = new KeyboardUsage(Component.Identifier.Key.SYSRQ, 70);
        SCROLLLOCK = new KeyboardUsage(Component.Identifier.Key.SCROLL, 71);
        PAUSE = new KeyboardUsage(Component.Identifier.Key.PAUSE, 72);
        INSERT = new KeyboardUsage(Component.Identifier.Key.INSERT, 73);
        HOME = new KeyboardUsage(Component.Identifier.Key.HOME, 74);
        PAGEUP = new KeyboardUsage(Component.Identifier.Key.PAGEUP, 75);
        DELETE = new KeyboardUsage(Component.Identifier.Key.DELETE, 76);
        END = new KeyboardUsage(Component.Identifier.Key.END, 77);
        PAGEDOWN = new KeyboardUsage(Component.Identifier.Key.PAGEDOWN, 78);
        RIGHTARROW = new KeyboardUsage(Component.Identifier.Key.RIGHT, 79);
        LEFTARROW = new KeyboardUsage(Component.Identifier.Key.LEFT, 80);
        DOWNARROW = new KeyboardUsage(Component.Identifier.Key.DOWN, 81);
        UPARROW = new KeyboardUsage(Component.Identifier.Key.UP, 82);
        KEYPAD_NUMLOCK = new KeyboardUsage(Component.Identifier.Key.NUMLOCK, 83);
        KEYPAD_SLASH = new KeyboardUsage(Component.Identifier.Key.DIVIDE, 84);
        KEYPAD_ASTERICK = new KeyboardUsage(85);
        KEYPAD_HYPHEN = new KeyboardUsage(Component.Identifier.Key.SUBTRACT, 86);
        KEYPAD_PLUS = new KeyboardUsage(Component.Identifier.Key.ADD, 87);
        KEYPAD_ENTER = new KeyboardUsage(Component.Identifier.Key.NUMPADENTER, 88);
        KEYPAD_1 = new KeyboardUsage(Component.Identifier.Key.NUMPAD1, 89);
        KEYPAD_2 = new KeyboardUsage(Component.Identifier.Key.NUMPAD2, 90);
        KEYPAD_3 = new KeyboardUsage(Component.Identifier.Key.NUMPAD3, 91);
        KEYPAD_4 = new KeyboardUsage(Component.Identifier.Key.NUMPAD4, 92);
        KEYPAD_5 = new KeyboardUsage(Component.Identifier.Key.NUMPAD5, 93);
        KEYPAD_6 = new KeyboardUsage(Component.Identifier.Key.NUMPAD6, 94);
        KEYPAD_7 = new KeyboardUsage(Component.Identifier.Key.NUMPAD7, 95);
        KEYPAD_8 = new KeyboardUsage(Component.Identifier.Key.NUMPAD8, 96);
        KEYPAD_9 = new KeyboardUsage(Component.Identifier.Key.NUMPAD9, 97);
        KEYPAD_0 = new KeyboardUsage(Component.Identifier.Key.NUMPAD0, 98);
        KEYPAD_PERIOD = new KeyboardUsage(Component.Identifier.Key.DECIMAL, 99);
        NONUSBACKSLASH = new KeyboardUsage(Component.Identifier.Key.BACKSLASH, 100);
        APPLICATION = new KeyboardUsage(Component.Identifier.Key.APPS, 101);
        POWER = new KeyboardUsage(Component.Identifier.Key.POWER, 102);
        KEYPAD_EQUALSIGN = new KeyboardUsage(Component.Identifier.Key.NUMPADEQUAL, 103);
        F13 = new KeyboardUsage(Component.Identifier.Key.F13, 104);
        F14 = new KeyboardUsage(Component.Identifier.Key.F14, 105);
        F15 = new KeyboardUsage(Component.Identifier.Key.F15, 106);
        F16 = new KeyboardUsage(107);
        F17 = new KeyboardUsage(108);
        F18 = new KeyboardUsage(109);
        F19 = new KeyboardUsage(110);
        F20 = new KeyboardUsage(111);
        F21 = new KeyboardUsage(112);
        F22 = new KeyboardUsage(113);
        F23 = new KeyboardUsage(114);
        F24 = new KeyboardUsage(115);
        EXECUTE = new KeyboardUsage(116);
        HELP = new KeyboardUsage(117);
        MENU = new KeyboardUsage(118);
        SELECT = new KeyboardUsage(119);
        STOP = new KeyboardUsage(Component.Identifier.Key.STOP, 120);
        AGAIN = new KeyboardUsage(121);
        UNDO = new KeyboardUsage(122);
        CUT = new KeyboardUsage(123);
        COPY = new KeyboardUsage(124);
        PASTE = new KeyboardUsage(125);
        FIND = new KeyboardUsage(126);
        MUTE = new KeyboardUsage(127);
        VOLUMEUP = new KeyboardUsage(128);
        VOLUMEDOWN = new KeyboardUsage(129);
        LOCKINGCAPSLOCK = new KeyboardUsage(Component.Identifier.Key.CAPITAL, 130);
        LOCKINGNUMLOCK = new KeyboardUsage(Component.Identifier.Key.NUMLOCK, 131);
        LOCKINGSCROLLLOCK = new KeyboardUsage(Component.Identifier.Key.SCROLL, 132);
        KEYPAD_COMMA = new KeyboardUsage(Component.Identifier.Key.COMMA, 133);
        KEYPAD_EQUALSSIGNAS400 = new KeyboardUsage(134);
        INTERNATIONAL1 = new KeyboardUsage(135);
        INTERNATIONAL2 = new KeyboardUsage(136);
        INTERNATIONAL3 = new KeyboardUsage(137);
        INTERNATIONAL4 = new KeyboardUsage(138);
        INTERNATIONAL5 = new KeyboardUsage(139);
        INTERNATIONAL6 = new KeyboardUsage(140);
        INTERNATIONAL7 = new KeyboardUsage(141);
        INTERNATIONAL8 = new KeyboardUsage(142);
        INTERNATIONAL9 = new KeyboardUsage(143);
        LANG1 = new KeyboardUsage(144);
        LANG2 = new KeyboardUsage(145);
        LANG3 = new KeyboardUsage(146);
        LANG4 = new KeyboardUsage(147);
        LANG5 = new KeyboardUsage(148);
        LANG6 = new KeyboardUsage(149);
        LANG7 = new KeyboardUsage(150);
        LANG8 = new KeyboardUsage(151);
        LANG9 = new KeyboardUsage(152);
        ALTERNATEERASE = new KeyboardUsage(153);
        SYSREQORATTENTION = new KeyboardUsage(Component.Identifier.Key.SYSRQ, 154);
        CANCEL = new KeyboardUsage(155);
        CLEAR = new KeyboardUsage(156);
        PRIOR = new KeyboardUsage(Component.Identifier.Key.PAGEUP, 157);
        RETURN = new KeyboardUsage(Component.Identifier.Key.RETURN, 158);
        SEPARATOR = new KeyboardUsage(159);
        OUT = new KeyboardUsage(160);
        OPER = new KeyboardUsage(161);
        CLEARORAGAIN = new KeyboardUsage(162);
        CRSELORPROPS = new KeyboardUsage(163);
        EXSEL = new KeyboardUsage(164);
        LEFTCONTROL = new KeyboardUsage(Component.Identifier.Key.LCONTROL, 224);
        LEFTSHIFT = new KeyboardUsage(Component.Identifier.Key.LSHIFT, 225);
        LEFTALT = new KeyboardUsage(Component.Identifier.Key.LALT, 226);
        LEFTGUI = new KeyboardUsage(Component.Identifier.Key.LWIN, 227);
        RIGHTCONTROL = new KeyboardUsage(Component.Identifier.Key.RCONTROL, 228);
        RIGHTSHIFT = new KeyboardUsage(Component.Identifier.Key.RSHIFT, 229);
        RIGHTALT = new KeyboardUsage(Component.Identifier.Key.RALT, 230);
        RIGHTGUI = new KeyboardUsage(Component.Identifier.Key.RWIN, 231);
    }
}
