package net.minecraft.init;

import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmorStand;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemEmptyMap;
import net.minecraft.item.ItemEnchantedBook;
import net.minecraft.item.ItemFishingRod;
import net.minecraft.item.ItemMap;
import net.minecraft.item.ItemPotion;
import net.minecraft.item.ItemShears;
import net.minecraft.util.ResourceLocation;

public class Items {
    public static final Item iron_shovel;
    public static final Item iron_pickaxe;
    public static final Item iron_axe;
    public static final Item flint_and_steel;
    public static final Item apple;
    public static final ItemBow bow;
    public static final Item arrow;
    public static final Item coal;
    public static final Item diamond;
    public static final Item iron_ingot;
    public static final Item gold_ingot;
    public static final Item iron_sword;
    public static final Item wooden_sword;
    public static final Item wooden_shovel;
    public static final Item wooden_pickaxe;
    public static final Item wooden_axe;
    public static final Item stone_sword;
    public static final Item stone_shovel;
    public static final Item stone_pickaxe;
    public static final Item stone_axe;
    public static final Item diamond_sword;
    public static final Item diamond_shovel;
    public static final Item diamond_pickaxe;
    public static final Item diamond_axe;
    public static final Item stick;
    public static final Item bowl;
    public static final Item mushroom_stew;
    public static final Item golden_sword;
    public static final Item golden_shovel;
    public static final Item golden_pickaxe;
    public static final Item golden_axe;
    public static final Item string;
    public static final Item feather;
    public static final Item gunpowder;
    public static final Item wooden_hoe;
    public static final Item stone_hoe;
    public static final Item iron_hoe;
    public static final Item diamond_hoe;
    public static final Item golden_hoe;
    public static final Item wheat_seeds;
    public static final Item wheat;
    public static final Item bread;
    public static final ItemArmor leather_helmet;
    public static final ItemArmor leather_chestplate;
    public static final ItemArmor leather_leggings;
    public static final ItemArmor leather_boots;
    public static final ItemArmor chainmail_helmet;
    public static final ItemArmor chainmail_chestplate;
    public static final ItemArmor chainmail_leggings;
    public static final ItemArmor chainmail_boots;
    public static final ItemArmor iron_helmet;
    public static final ItemArmor iron_chestplate;
    public static final ItemArmor iron_leggings;
    public static final ItemArmor iron_boots;
    public static final ItemArmor diamond_helmet;
    public static final ItemArmor diamond_chestplate;
    public static final ItemArmor diamond_leggings;
    public static final ItemArmor diamond_boots;
    public static final ItemArmor golden_helmet;
    public static final ItemArmor golden_chestplate;
    public static final ItemArmor golden_leggings;
    public static final ItemArmor golden_boots;
    public static final Item flint;
    public static final Item porkchop;
    public static final Item cooked_porkchop;
    public static final Item painting;
    public static final Item golden_apple;
    public static final Item sign;
    public static final Item oak_door;
    public static final Item spruce_door;
    public static final Item birch_door;
    public static final Item jungle_door;
    public static final Item acacia_door;
    public static final Item dark_oak_door;
    public static final Item bucket;
    public static final Item water_bucket;
    public static final Item lava_bucket;
    public static final Item minecart;
    public static final Item saddle;
    public static final Item iron_door;
    public static final Item redstone;
    public static final Item snowball;
    public static final Item boat;
    public static final Item leather;
    public static final Item milk_bucket;
    public static final Item brick;
    public static final Item clay_ball;
    public static final Item reeds;
    public static final Item paper;
    public static final Item book;
    public static final Item slime_ball;
    public static final Item chest_minecart;
    public static final Item furnace_minecart;
    public static final Item egg;
    public static final Item compass;
    public static final ItemFishingRod fishing_rod;
    public static final Item clock;
    public static final Item glowstone_dust;
    public static final Item fish;
    public static final Item cooked_fish;
    public static final Item dye;
    public static final Item bone;
    public static final Item sugar;
    public static final Item cake;
    public static final Item bed;
    public static final Item repeater;
    public static final Item cookie;
    public static final ItemMap filled_map;
    public static final ItemShears shears;
    public static final Item melon;
    public static final Item pumpkin_seeds;
    public static final Item melon_seeds;
    public static final Item beef;
    public static final Item cooked_beef;
    public static final Item chicken;
    public static final Item cooked_chicken;
    public static final Item mutton;
    public static final Item cooked_mutton;
    public static final Item rabbit;
    public static final Item cooked_rabbit;
    public static final Item rabbit_stew;
    public static final Item rabbit_foot;
    public static final Item rabbit_hide;
    public static final Item rotten_flesh;
    public static final Item ender_pearl;
    public static final Item blaze_rod;
    public static final Item ghast_tear;
    public static final Item gold_nugget;
    public static final Item nether_wart;
    public static final ItemPotion potionitem;
    public static final Item glass_bottle;
    public static final Item spider_eye;
    public static final Item fermented_spider_eye;
    public static final Item blaze_powder;
    public static final Item magma_cream;
    public static final Item brewing_stand;
    public static final Item cauldron;
    public static final Item ender_eye;
    public static final Item speckled_melon;
    public static final Item spawn_egg;
    public static final Item experience_bottle;
    public static final Item fire_charge;
    public static final Item writable_book;
    public static final Item written_book;
    public static final Item emerald;
    public static final Item item_frame;
    public static final Item flower_pot;
    public static final Item carrot;
    public static final Item potato;
    public static final Item baked_potato;
    public static final Item poisonous_potato;
    public static final ItemEmptyMap map;
    public static final Item golden_carrot;
    public static final Item skull;
    public static final Item carrot_on_a_stick;
    public static final Item nether_star;
    public static final Item pumpkin_pie;
    public static final Item fireworks;
    public static final Item firework_charge;
    public static final ItemEnchantedBook enchanted_book;
    public static final Item comparator;
    public static final Item netherbrick;
    public static final Item quartz;
    public static final Item tnt_minecart;
    public static final Item hopper_minecart;
    public static final ItemArmorStand armor_stand;
    public static final Item iron_horse_armor;
    public static final Item golden_horse_armor;
    public static final Item diamond_horse_armor;
    public static final Item lead;
    public static final Item name_tag;
    public static final Item command_block_minecart;
    public static final Item record_13;
    public static final Item record_cat;
    public static final Item record_blocks;
    public static final Item record_chirp;
    public static final Item record_far;
    public static final Item record_mall;
    public static final Item record_mellohi;
    public static final Item record_stal;
    public static final Item record_strad;
    public static final Item record_ward;
    public static final Item record_11;
    public static final Item record_wait;
    public static final Item prismarine_shard;
    public static final Item prismarine_crystals;
    public static final Item banner;
    private static final String __OBFID = "CL_00000044";

    private static Item getRegisteredItem(String p_179554_0_) {
        return (Item) Item.itemRegistry.getObject(new ResourceLocation(p_179554_0_));
    }

    static {
        if (!Bootstrap.isRegistered()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        } else {
            iron_shovel = Items.getRegisteredItem("iron_shovel");
            iron_pickaxe = Items.getRegisteredItem("iron_pickaxe");
            iron_axe = Items.getRegisteredItem("iron_axe");
            flint_and_steel = Items.getRegisteredItem("flint_and_steel");
            apple = Items.getRegisteredItem("apple");
            bow = (ItemBow) Items.getRegisteredItem("bow");
            arrow = Items.getRegisteredItem("arrow");
            coal = Items.getRegisteredItem("coal");
            diamond = Items.getRegisteredItem("diamond");
            iron_ingot = Items.getRegisteredItem("iron_ingot");
            gold_ingot = Items.getRegisteredItem("gold_ingot");
            iron_sword = Items.getRegisteredItem("iron_sword");
            wooden_sword = Items.getRegisteredItem("wooden_sword");
            wooden_shovel = Items.getRegisteredItem("wooden_shovel");
            wooden_pickaxe = Items.getRegisteredItem("wooden_pickaxe");
            wooden_axe = Items.getRegisteredItem("wooden_axe");
            stone_sword = Items.getRegisteredItem("stone_sword");
            stone_shovel = Items.getRegisteredItem("stone_shovel");
            stone_pickaxe = Items.getRegisteredItem("stone_pickaxe");
            stone_axe = Items.getRegisteredItem("stone_axe");
            diamond_sword = Items.getRegisteredItem("diamond_sword");
            diamond_shovel = Items.getRegisteredItem("diamond_shovel");
            diamond_pickaxe = Items.getRegisteredItem("diamond_pickaxe");
            diamond_axe = Items.getRegisteredItem("diamond_axe");
            stick = Items.getRegisteredItem("stick");
            bowl = Items.getRegisteredItem("bowl");
            mushroom_stew = Items.getRegisteredItem("mushroom_stew");
            golden_sword = Items.getRegisteredItem("golden_sword");
            golden_shovel = Items.getRegisteredItem("golden_shovel");
            golden_pickaxe = Items.getRegisteredItem("golden_pickaxe");
            golden_axe = Items.getRegisteredItem("golden_axe");
            string = Items.getRegisteredItem("string");
            feather = Items.getRegisteredItem("feather");
            gunpowder = Items.getRegisteredItem("gunpowder");
            wooden_hoe = Items.getRegisteredItem("wooden_hoe");
            stone_hoe = Items.getRegisteredItem("stone_hoe");
            iron_hoe = Items.getRegisteredItem("iron_hoe");
            diamond_hoe = Items.getRegisteredItem("diamond_hoe");
            golden_hoe = Items.getRegisteredItem("golden_hoe");
            wheat_seeds = Items.getRegisteredItem("wheat_seeds");
            wheat = Items.getRegisteredItem("wheat");
            bread = Items.getRegisteredItem("bread");
            leather_helmet = (ItemArmor) Items.getRegisteredItem("leather_helmet");
            leather_chestplate = (ItemArmor) Items.getRegisteredItem("leather_chestplate");
            leather_leggings = (ItemArmor) Items.getRegisteredItem("leather_leggings");
            leather_boots = (ItemArmor) Items.getRegisteredItem("leather_boots");
            chainmail_helmet = (ItemArmor) Items.getRegisteredItem("chainmail_helmet");
            chainmail_chestplate = (ItemArmor) Items.getRegisteredItem("chainmail_chestplate");
            chainmail_leggings = (ItemArmor) Items.getRegisteredItem("chainmail_leggings");
            chainmail_boots = (ItemArmor) Items.getRegisteredItem("chainmail_boots");
            iron_helmet = (ItemArmor) Items.getRegisteredItem("iron_helmet");
            iron_chestplate = (ItemArmor) Items.getRegisteredItem("iron_chestplate");
            iron_leggings = (ItemArmor) Items.getRegisteredItem("iron_leggings");
            iron_boots = (ItemArmor) Items.getRegisteredItem("iron_boots");
            diamond_helmet = (ItemArmor) Items.getRegisteredItem("diamond_helmet");
            diamond_chestplate = (ItemArmor) Items.getRegisteredItem("diamond_chestplate");
            diamond_leggings = (ItemArmor) Items.getRegisteredItem("diamond_leggings");
            diamond_boots = (ItemArmor) Items.getRegisteredItem("diamond_boots");
            golden_helmet = (ItemArmor) Items.getRegisteredItem("golden_helmet");
            golden_chestplate = (ItemArmor) Items.getRegisteredItem("golden_chestplate");
            golden_leggings = (ItemArmor) Items.getRegisteredItem("golden_leggings");
            golden_boots = (ItemArmor) Items.getRegisteredItem("golden_boots");
            flint = Items.getRegisteredItem("flint");
            porkchop = Items.getRegisteredItem("porkchop");
            cooked_porkchop = Items.getRegisteredItem("cooked_porkchop");
            painting = Items.getRegisteredItem("painting");
            golden_apple = Items.getRegisteredItem("golden_apple");
            sign = Items.getRegisteredItem("sign");
            oak_door = Items.getRegisteredItem("wooden_door");
            spruce_door = Items.getRegisteredItem("spruce_door");
            birch_door = Items.getRegisteredItem("birch_door");
            jungle_door = Items.getRegisteredItem("jungle_door");
            acacia_door = Items.getRegisteredItem("acacia_door");
            dark_oak_door = Items.getRegisteredItem("dark_oak_door");
            bucket = Items.getRegisteredItem("bucket");
            water_bucket = Items.getRegisteredItem("water_bucket");
            lava_bucket = Items.getRegisteredItem("lava_bucket");
            minecart = Items.getRegisteredItem("minecart");
            saddle = Items.getRegisteredItem("saddle");
            iron_door = Items.getRegisteredItem("iron_door");
            redstone = Items.getRegisteredItem("redstone");
            snowball = Items.getRegisteredItem("snowball");
            boat = Items.getRegisteredItem("boat");
            leather = Items.getRegisteredItem("leather");
            milk_bucket = Items.getRegisteredItem("milk_bucket");
            brick = Items.getRegisteredItem("brick");
            clay_ball = Items.getRegisteredItem("clay_ball");
            reeds = Items.getRegisteredItem("reeds");
            paper = Items.getRegisteredItem("paper");
            book = Items.getRegisteredItem("book");
            slime_ball = Items.getRegisteredItem("slime_ball");
            chest_minecart = Items.getRegisteredItem("chest_minecart");
            furnace_minecart = Items.getRegisteredItem("furnace_minecart");
            egg = Items.getRegisteredItem("egg");
            compass = Items.getRegisteredItem("compass");
            fishing_rod = (ItemFishingRod) Items.getRegisteredItem("fishing_rod");
            clock = Items.getRegisteredItem("clock");
            glowstone_dust = Items.getRegisteredItem("glowstone_dust");
            fish = Items.getRegisteredItem("fish");
            cooked_fish = Items.getRegisteredItem("cooked_fish");
            dye = Items.getRegisteredItem("dye");
            bone = Items.getRegisteredItem("bone");
            sugar = Items.getRegisteredItem("sugar");
            cake = Items.getRegisteredItem("cake");
            bed = Items.getRegisteredItem("bed");
            repeater = Items.getRegisteredItem("repeater");
            cookie = Items.getRegisteredItem("cookie");
            filled_map = (ItemMap) Items.getRegisteredItem("filled_map");
            shears = (ItemShears) Items.getRegisteredItem("shears");
            melon = Items.getRegisteredItem("melon");
            pumpkin_seeds = Items.getRegisteredItem("pumpkin_seeds");
            melon_seeds = Items.getRegisteredItem("melon_seeds");
            beef = Items.getRegisteredItem("beef");
            cooked_beef = Items.getRegisteredItem("cooked_beef");
            chicken = Items.getRegisteredItem("chicken");
            cooked_chicken = Items.getRegisteredItem("cooked_chicken");
            mutton = Items.getRegisteredItem("mutton");
            cooked_mutton = Items.getRegisteredItem("cooked_mutton");
            rabbit = Items.getRegisteredItem("rabbit");
            cooked_rabbit = Items.getRegisteredItem("cooked_rabbit");
            rabbit_stew = Items.getRegisteredItem("rabbit_stew");
            rabbit_foot = Items.getRegisteredItem("rabbit_foot");
            rabbit_hide = Items.getRegisteredItem("rabbit_hide");
            rotten_flesh = Items.getRegisteredItem("rotten_flesh");
            ender_pearl = Items.getRegisteredItem("ender_pearl");
            blaze_rod = Items.getRegisteredItem("blaze_rod");
            ghast_tear = Items.getRegisteredItem("ghast_tear");
            gold_nugget = Items.getRegisteredItem("gold_nugget");
            nether_wart = Items.getRegisteredItem("nether_wart");
            potionitem = (ItemPotion) Items.getRegisteredItem("potion");
            glass_bottle = Items.getRegisteredItem("glass_bottle");
            spider_eye = Items.getRegisteredItem("spider_eye");
            fermented_spider_eye = Items.getRegisteredItem("fermented_spider_eye");
            blaze_powder = Items.getRegisteredItem("blaze_powder");
            magma_cream = Items.getRegisteredItem("magma_cream");
            brewing_stand = Items.getRegisteredItem("brewing_stand");
            cauldron = Items.getRegisteredItem("cauldron");
            ender_eye = Items.getRegisteredItem("ender_eye");
            speckled_melon = Items.getRegisteredItem("speckled_melon");
            spawn_egg = Items.getRegisteredItem("spawn_egg");
            experience_bottle = Items.getRegisteredItem("experience_bottle");
            fire_charge = Items.getRegisteredItem("fire_charge");
            writable_book = Items.getRegisteredItem("writable_book");
            written_book = Items.getRegisteredItem("written_book");
            emerald = Items.getRegisteredItem("emerald");
            item_frame = Items.getRegisteredItem("item_frame");
            flower_pot = Items.getRegisteredItem("flower_pot");
            carrot = Items.getRegisteredItem("carrot");
            potato = Items.getRegisteredItem("potato");
            baked_potato = Items.getRegisteredItem("baked_potato");
            poisonous_potato = Items.getRegisteredItem("poisonous_potato");
            map = (ItemEmptyMap) Items.getRegisteredItem("map");
            golden_carrot = Items.getRegisteredItem("golden_carrot");
            skull = Items.getRegisteredItem("skull");
            carrot_on_a_stick = Items.getRegisteredItem("carrot_on_a_stick");
            nether_star = Items.getRegisteredItem("nether_star");
            pumpkin_pie = Items.getRegisteredItem("pumpkin_pie");
            fireworks = Items.getRegisteredItem("fireworks");
            firework_charge = Items.getRegisteredItem("firework_charge");
            enchanted_book = (ItemEnchantedBook) Items.getRegisteredItem("enchanted_book");
            comparator = Items.getRegisteredItem("comparator");
            netherbrick = Items.getRegisteredItem("netherbrick");
            quartz = Items.getRegisteredItem("quartz");
            tnt_minecart = Items.getRegisteredItem("tnt_minecart");
            hopper_minecart = Items.getRegisteredItem("hopper_minecart");
            armor_stand = (ItemArmorStand) Items.getRegisteredItem("armor_stand");
            iron_horse_armor = Items.getRegisteredItem("iron_horse_armor");
            golden_horse_armor = Items.getRegisteredItem("golden_horse_armor");
            diamond_horse_armor = Items.getRegisteredItem("diamond_horse_armor");
            lead = Items.getRegisteredItem("lead");
            name_tag = Items.getRegisteredItem("name_tag");
            command_block_minecart = Items.getRegisteredItem("command_block_minecart");
            record_13 = Items.getRegisteredItem("record_13");
            record_cat = Items.getRegisteredItem("record_cat");
            record_blocks = Items.getRegisteredItem("record_blocks");
            record_chirp = Items.getRegisteredItem("record_chirp");
            record_far = Items.getRegisteredItem("record_far");
            record_mall = Items.getRegisteredItem("record_mall");
            record_mellohi = Items.getRegisteredItem("record_mellohi");
            record_stal = Items.getRegisteredItem("record_stal");
            record_strad = Items.getRegisteredItem("record_strad");
            record_ward = Items.getRegisteredItem("record_ward");
            record_11 = Items.getRegisteredItem("record_11");
            record_wait = Items.getRegisteredItem("record_wait");
            prismarine_shard = Items.getRegisteredItem("prismarine_shard");
            prismarine_crystals = Items.getRegisteredItem("prismarine_crystals");
            banner = Items.getRegisteredItem("banner");
        }
    }
}
