/*
 * Decompiled with CFR 0_132 Helper by Lightcolour E-mail wyy-666@hotmail.com.
 */
package me.slowly.client.mod;

import java.util.ArrayList;
import me.slowly.client.mod.Mod;
import me.slowly.client.mod.mods.combat.AutoClicker;
import me.slowly.client.mod.mods.combat.AutoPot;
import me.slowly.client.mod.mods.combat.AutoSoup;
import me.slowly.client.mod.mods.combat.BowAimbot;
import me.slowly.client.mod.mods.combat.Criticals;
import me.slowly.client.mod.mods.combat.FastBow;
import me.slowly.client.mod.mods.combat.Hitbox;
import me.slowly.client.mod.mods.combat.KeepSprint;
import me.slowly.client.mod.mods.combat.KillAura;
import me.slowly.client.mod.mods.combat.MusicHack;
import me.slowly.client.mod.mods.combat.NoFriends;
import me.slowly.client.mod.mods.combat.Reach;
import me.slowly.client.mod.mods.combat.SuperHit;
import me.slowly.client.mod.mods.combat.TNTBlock;
import me.slowly.client.mod.mods.combat.Velocity;
import me.slowly.client.mod.mods.misc.AutoArmor;
import me.slowly.client.mod.mods.misc.AutoRespawn;
import me.slowly.client.mod.mods.misc.BlockParty;
import me.slowly.client.mod.mods.misc.ChestStealer;
import me.slowly.client.mod.mods.misc.Eagle;
import me.slowly.client.mod.mods.misc.FastPlace;
import me.slowly.client.mod.mods.misc.Fucker;
import me.slowly.client.mod.mods.misc.InvCleaner;
import me.slowly.client.mod.mods.misc.NameProtect;
import me.slowly.client.mod.mods.misc.NoBob;
import me.slowly.client.mod.mods.misc.NoFov;
import me.slowly.client.mod.mods.misc.NoHurtcam;
import me.slowly.client.mod.mods.misc.SafeWalk;
import me.slowly.client.mod.mods.misc.Spammer;
import me.slowly.client.mod.mods.misc.Teams;
import me.slowly.client.mod.mods.misc.Timer;
import me.slowly.client.mod.mods.movement.AACLongJumpFix;
import me.slowly.client.mod.mods.movement.FastLadder;
import me.slowly.client.mod.mods.movement.FastStairs;
import me.slowly.client.mod.mods.movement.Fly;
import me.slowly.client.mod.mods.movement.HighJump;
import me.slowly.client.mod.mods.movement.InventoryMove;
import me.slowly.client.mod.mods.movement.Jesus;
import me.slowly.client.mod.mods.movement.LiquidJump;
import me.slowly.client.mod.mods.movement.LongJump;
import me.slowly.client.mod.mods.movement.NoSlowdown;
import me.slowly.client.mod.mods.movement.ScaffoldWalk;
import me.slowly.client.mod.mods.movement.SlimeJump;
import me.slowly.client.mod.mods.movement.Speed;
import me.slowly.client.mod.mods.movement.Sprint;
import me.slowly.client.mod.mods.movement.Step;
import me.slowly.client.mod.mods.movement.Strafe;
import me.slowly.client.mod.mods.movement.TerrainSpeed;
import me.slowly.client.mod.mods.movement.Tower;
import me.slowly.client.mod.mods.movement.WaterSpeed;
import me.slowly.client.mod.mods.other.Gui;
import me.slowly.client.mod.mods.player.Blink;
import me.slowly.client.mod.mods.player.Crasher;
import me.slowly.client.mod.mods.player.Freecam;
import me.slowly.client.mod.mods.player.GodMode;
import me.slowly.client.mod.mods.player.ItemTeleport;
import me.slowly.client.mod.mods.player.MidClickFriends;
import me.slowly.client.mod.mods.player.NoClip;
import me.slowly.client.mod.mods.player.NoFall;
import me.slowly.client.mod.mods.player.NoPitchLimit;
import me.slowly.client.mod.mods.player.NoRotationSet;
import me.slowly.client.mod.mods.player.Phase;
import me.slowly.client.mod.mods.player.PotionSaver;
import me.slowly.client.mod.mods.player.Regen;
import me.slowly.client.mod.mods.player.Spider;
import me.slowly.client.mod.mods.player.Teleport;
import me.slowly.client.mod.mods.render.BlockESP;
import me.slowly.client.mod.mods.render.BlockHighlight;
import me.slowly.client.mod.mods.render.Chams;
import me.slowly.client.mod.mods.render.ChestESP;
import me.slowly.client.mod.mods.render.Direction;
import me.slowly.client.mod.mods.render.ESP;
import me.slowly.client.mod.mods.render.Fullbright;
import me.slowly.client.mod.mods.render.GetDown;
import me.slowly.client.mod.mods.render.HUD;
import me.slowly.client.mod.mods.render.ItemESP;
import me.slowly.client.mod.mods.render.ItemPhysics;
import me.slowly.client.mod.mods.render.Light;
import me.slowly.client.mod.mods.render.NameTags;
import me.slowly.client.mod.mods.render.Radar;
import me.slowly.client.mod.mods.render.StreamMode;
import me.slowly.client.mod.mods.render.SwingAnimation;
import me.slowly.client.mod.mods.render.Tracers;
import me.slowly.client.mod.mods.render.Trajectories;
import me.slowly.client.mod.mods.world.AntiBots;
import me.slowly.client.mod.mods.world.AntiCactus;
import me.slowly.client.mod.mods.world.AntiFire;
import me.slowly.client.mod.mods.world.AntiInvis;
import me.slowly.client.mod.mods.world.AutoL;
import me.slowly.client.mod.mods.world.ChestAura;
import me.slowly.client.mod.mods.world.FastConsume;
import me.slowly.client.mod.mods.world.IRC;
import me.slowly.client.mod.mods.world.NMSLFW;
import me.slowly.client.mod.mods.world.NoWeb;
import me.slowly.client.mod.mods.world.SpeedMine;

public class ModManager {
    private static ArrayList<Mod> modList = new ArrayList();
    public static ArrayList<Mod> sortedModList = new ArrayList();

    public ModManager() {
        modList.add(new Gui());
        modList.add(new IRC());
        modList.add(new MusicHack());
        modList.add(new Reach());
        modList.add(new Hitbox());
        modList.add(new KeepSprint());
        modList.add(new Radar());
        modList.add(new AutoL());
        modList.add(new NoHurtcam());
        modList.add(new HUD());
        modList.add(new TNTBlock());
        modList.add(new FastLadder());
        modList.add(new FastPlace());
        modList.add(new Fullbright());
        modList.add(new Teams());
        modList.add(new Sprint());
        modList.add(new Freecam());
        modList.add(new InventoryMove());
        modList.add(new FastBow());
        modList.add(new SpeedMine());
        modList.add(new TerrainSpeed());
        modList.add(new Tower());
        modList.add(new NMSLFW());
        modList.add(new Eagle());
        modList.add(new WaterSpeed());
        modList.add(new FastStairs());
        modList.add(new NoFall());
        modList.add(new BlockESP());
        modList.add(new Fly());
        modList.add(new GodMode());
        modList.add(new Crasher());
        modList.add(new Velocity());
        modList.add(new ScaffoldWalk());
        modList.add(new Step());
        modList.add(new Phase());
        modList.add(new BlockHighlight());
        modList.add(new Regen());
        modList.add(new ItemPhysics());
        modList.add(new ItemTeleport());
        modList.add(new ChestAura());
        modList.add(new NameProtect());
        modList.add(new Light());
        modList.add(new NoRotationSet());
        modList.add(new Criticals());
        modList.add(new AntiBots());
        modList.add(new SwingAnimation());
        modList.add(new Tracers());
        modList.add(new GetDown());
        modList.add(new SuperHit());
        modList.add(new Teleport());
        modList.add(new BlockParty());
        modList.add(new StreamMode());
        modList.add(new ChestESP());
        modList.add(new Direction());
        modList.add(new NoFriends());
        modList.add(new NoWeb());
        modList.add(new AntiInvis());
        modList.add(new ESP());
        modList.add(new Trajectories());
        modList.add(new ItemESP());
        modList.add(new NoClip());
        modList.add(new Blink());
        modList.add(new AntiFire());
        modList.add(new Chams());
        modList.add(new AntiCactus());
        modList.add(new Fucker());
        modList.add(new NoBob());
        modList.add(new NoFov());
        modList.add(new MidClickFriends());
        modList.add(new KillAura());
        modList.add(new BowAimbot());
        modList.add(new NameTags());
        modList.add(new PotionSaver());
        modList.add(new ChestStealer());
        modList.add(new AutoPot());
        modList.add(new AutoSoup());
        modList.add(new AutoClicker());
        modList.add(new LongJump());
        modList.add(new Spammer());
        modList.add(new FastConsume());
        modList.add(new NoSlowdown());
        modList.add(new Timer());
        modList.add(new AutoArmor());
        modList.add(new Spider());
        modList.add(new InvCleaner());
        modList.add(new SlimeJump());
        modList.add(new Speed());
        modList.add(new HighJump());
        modList.add(new Jesus());
        modList.add(new SafeWalk());
        modList.add(new AutoRespawn());
        modList.add(new AACLongJumpFix());
        modList.add(new LiquidJump());
        modList.add(new Strafe());
        modList.add(new NoPitchLimit());
        sortedModList = (ArrayList)modList.clone();
    }

    public static ArrayList<Mod> getModList() {
        return modList;
    }

    public static Mod getModByName(String mod) {
        for (Mod m : modList) {
            if (!m.getName().equalsIgnoreCase(mod)) continue;
            return m;
        }
        return null;
    }
}

